// Generated by CoffeeScript 1.12.2
(function() {
  define(["apps/streams/app", "apps/header/app", "apps/footer/app", "apps/d3/app", "apps/about/app", "apps/playa/app", "apps/games/app"], function() {});

}).call(this);
