// Generated by CoffeeScript 1.9.2
(function() {
  define(["apps/header/app", "apps/footer/app", "apps/games/app", "apps/d3/app", "apps/about/app", "apps/streams/app", "apps/playa/app"], function() {});

}).call(this);
