// Generated by CoffeeScript 1.12.1
(function() {
  define(function(require) {
    return {
      player: require("text!apps/playa/show/templates/player.htm"),
      user: require("text!apps/playa/show/templates/user.htm"),
      layout: require("text!apps/playa/show/templates/layout.htm"),
      chat: require("text!apps/playa/show/templates/chat.htm")
    };
  });

}).call(this);
