// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['apps/playa/show/templates', 'views/_base', 'swf'], function(Templates, AppView, swf) {
    var Chat, Layout, Player, User, _ref, _ref1, _ref2, _ref3;
    return {
      Player: Player = (function(_super) {
        __extends(Player, _super);

        function Player() {
          _ref = Player.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        Player.prototype.template = _.template(Templates.player);

        Player.prototype.ui = {
          panelbody: ".panel-body"
        };

        Player.prototype.onShow = function() {
          var $height, $width, flashvars, params;
          $width = this.ui.panelbody.outerWidth(false);
          $height = Math.floor($width * 9 / 16);
          flashvars = false;
          params = {
            allowFullScreen: "true",
            wmode: "transparent",
            allowScriptAccess: "always",
            allowNetworking: "all",
            flashvars: "hostname=www.twitch.tv&channel=" + (this.model.get("channel").display_name) + "&start_volume=15&auto_play=true&client_id=hqxyqc9bf41e6grm6txrsdcwncoxavz&res=720p"
          };
          return swf.embedSWF("https://www-cdn.jtvnw.net/widgets/live_embed_player.swf?channel=" + (this.model.get("channel").display_name) + "&auto_play=true", "twitchplayer", $width, $height, "9", null, flashvars, params, {});
        };

        return Player;

      })(AppView.ItemView),
      User: User = (function(_super) {
        __extends(User, _super);

        function User() {
          _ref1 = User.__super__.constructor.apply(this, arguments);
          return _ref1;
        }

        User.prototype.template = _.template(Templates.user);

        return User;

      })(AppView.ItemView),
      Chat: Chat = (function(_super) {
        __extends(Chat, _super);

        function Chat() {
          _ref2 = Chat.__super__.constructor.apply(this, arguments);
          return _ref2;
        }

        Chat.prototype.template = _.template(Templates.chat);

        return Chat;

      })(AppView.ItemView),
      Layout: Layout = (function(_super) {
        __extends(Layout, _super);

        function Layout() {
          _ref3 = Layout.__super__.constructor.apply(this, arguments);
          return _ref3;
        }

        Layout.prototype.template = _.template(Templates.layout);

        Layout.prototype.regions = {
          playerRegion: "#player-region",
          userRegion: "#user-region",
          chatRegion: "#chat-region"
        };

        return Layout;

      })(AppView.Layout)
    };
  });

}).call(this);
