// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["msgbus", "apps/footer/show/views", "controller/_base"], function(msgBus, View, AppController) {
    var Controller, _ref;
    return Controller = (function(_super) {
      __extends(Controller, _super);

      function Controller() {
        _ref = Controller.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Controller.prototype.initialize = function() {
        var author, footerView;
        author = msgBus.reqres.request("get:authorModel:info");
        footerView = this.getFooterView(author);
        return this.show(footerView);
      };

      Controller.prototype.getFooterView = function(model) {
        return new View.ItemView({
          model: model
        });
      };

      return Controller;

    })(AppController);
  });

}).call(this);
