// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['views/_base', 'apps/footer/show/templates'], function(AppViews, Templates) {
    var ShowFooterView, _ref;
    return {
      ItemView: ShowFooterView = (function(_super) {
        __extends(ShowFooterView, _super);

        function ShowFooterView() {
          _ref = ShowFooterView.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        ShowFooterView.prototype.template = _.template(Templates.footer);

        ShowFooterView.prototype.modelEvents = {
          "change": "render"
        };

        return ShowFooterView;

      })(AppViews.ItemView)
    };
  });

}).call(this);
