// Generated by CoffeeScript 1.12.2
(function() {
  define(["backbone", "marionette", "msgbus", "apps/load"], function(Backbone, Marionette, msgBus) {
    var app, appChannel;
    appChannel = msgBus.appChannel;
    app = new Marionette.Application({
      region: "#main-region",
      onBeforeStart: function(options) {
        if (options == null) {
          options = {};
        }
        appChannel.trigger("start:header:app");
        appChannel.trigger("start:footer:app");
        appChannel.trigger("start:d3:app");
        appChannel.trigger("start:about:app");
        appChannel.trigger("start:games:app");
        return appChannel.trigger("start:playa:app");
      },
      onStart: function() {
        var appstate, frag, match;
        appstate = appChannel.request("get:current:appstate");
        if (Backbone.history) {
          Backbone.history.start();
          frag = Backbone.history.fragment;
          match = /access_token/i.test(frag);
          if (match) {
            appstate.set("accessToken", frag.split(/[=&]/)[1]);
            appstate.set({
              "authState": true
            });
            return Backbone.history.navigate("#games", {
              trigger: true
            });
          } else {
            appstate.set({
              "authState": false
            });
            return Backbone.history.navigate("#about", {
              trigger: true
            });
          }
        }
      }
    });
    appChannel.reply("default:region", function() {
      return app.getRegion();
    });
    return app;
  });

}).call(this);
