// Generated by CoffeeScript 1.12.2
(function() {
  require.config({
    paths: {
      jquery: "../bower_components/jquery/dist/jquery",
      underscore: "../bower_components/underscore/underscore",
      backbone: "../bower_components/backbone/backbone",
      marionette: "../bower_components/backbone.marionette/lib/backbone.marionette",
      "backbone.radio": "../bower_components/backbone.radio/build/backbone.radio",
      moment: "../bower_components/moment/moment",
      globalize: "../bower_components/globalize/lib/globalize",
      text: "../bower_components/requirejs-text/text",
      d3: "../bower_components/d3/d3",
      spin: "../bower_components/spin.js/spin",
      jqueryspin: "../bower_components/spin.js/jquery.spin",
      bootstrap: "../bower_components/bootstrap/dist/js/bootstrap"
    },
    shim: {
      bootstrap: ["jquery"]
    }
  });

  require(["config/load", "app"], function(_config, app) {
    return app.start();
  });

}).call(this);
