// Generated by CoffeeScript 1.6.3
(function() {
  require.config({
    paths: {
      jquery: "../bower_components/jquery/jquery",
      underscore: "../bower_components/underscore-amd/underscore",
      backbone: "../bower_components/backbone-amd/backbone",
      "backbone.babysitter": "../bower_components/backbone.babysitter/lib/amd/backbone.babysitter",
      "backbone.wreqr": "../bower_components/backbone.wreqr/lib/amd/backbone.wreqr",
      "backbone.syphon": "../bower_components/backbone.syphon/lib/amd/backbone.syphon",
      marionette: "../bower_components/marionette/lib/core/amd/backbone.marionette",
      moment: "../bower_components/moment/moment",
      globalize: "../bower_components/globalize/lib/globalize",
      text: "../bower_components/requirejs-text/text",
      d3: "../bower_components/d3/d3",
      spin: "../bower_components/spin.js/spin",
      jqueryspin: "../bower_components/spin.js/jquery.spin",
      mockjax: "../bower_components/jquery-mockjax/jquery.mockjax",
      mockjson: "../bower_components/mockJSON/js/jquery.mockjson",
      holderjs: "../bower_components/holderjs/holder",
      bootstrap: "../bower_components/bootstrap/dist/js/bootstrap"
    },
    shim: {
      mockjax: ["jquery"],
      mockjson: ["jquery"],
      bootstrap: ["jquery"]
    }
  });

  require(["config/load", "app"], function(_config, app) {
    return app.start();
  });

}).call(this);
