// Generated by CoffeeScript 1.12.1
(function() {
  require.config({
    paths: {
      backbone: "../bower_components/backbone/backbone",
      underscore: "../bower_components/underscore/underscore",
      jquery: "../bower_components/jquery/dist/jquery",
      marionette: "../bower_components/marionette/lib/backbone.marionette",
      "backbone.syphon": "../bower_components/backbone.syphon/lib/backbone.syphon",
      moment: "../bower_components/moment/moment",
      globalize: "../bower_components/globalize/lib/globalize",
      text: "../bower_components/text/text",
      d3: "../bower_components/d3/d3",
      spin: "../bower_components/spin.js/spin",
      jqueryspin: "../bower_components/spin.js/jquery.spin",
      bootstrap: "../bower_components/bootstrap/dist/js/bootstrap"
    },
    shim: {
      bootstrap: ["jquery"]
    }
  });

  require(["config/load", "app"], function(_config, app) {
    return app.start();
  });

}).call(this);
