// Generated by CoffeeScript 1.12.2
(function() {
  define(["backbone", "backbone.radio"], function(Backbone) {
    return {
      appChannel: new Backbone.Radio.channel("app"),
      dataChannel: new Backbone.Radio.channel("data")
    };
  });

}).call(this);
