// Generated by CoffeeScript 1.12.2
(function() {
  define(["msgbus", "apps/footer/show/controller"], function(msgBus, Controller) {
    var API, appChannel;
    appChannel = msgBus.appChannel;
    API = {
      show: function() {
        return new Controller;
      }
    };
    return appChannel.on("start:footer:app", function() {
      return API.show();
    });
  });

}).call(this);
