// Generated by CoffeeScript 1.9.2
(function() {
  var API;

  define(["msgbus", "apps/footer/show/controller"], function(msgBus, Controller) {
    var channel;
    return channel = msgBus.appChannel;
  });

  API = {
    show: function() {
      return new Controller({
        region: channel.request("footer:region")
      });
    }
  };

  channel.on("start:footer:app", function() {
    return API.show();
  });

}).call(this);
