// Generated by CoffeeScript 1.12.2
(function() {
  define(["backbone", "msgbus"], function(Backbone, msgBus) {
    var _sync, appChannel, methods;
    appChannel = msgBus.appChannel;
    _sync = Backbone.sync;
    Backbone.sync = function(method, entity, options) {
      var sync;
      if (options == null) {
        options = {};
      }
      _.defaults(options, {
        beforeSend: _.bind(methods.beforeSend, entity),
        complete: _.bind(methods.complete, entity)
      });
      sync = _sync(method, entity, options);
      if (!entity._fetch && method === "read") {
        entity._fetch = sync;
      }
      return sync;
    };
    methods = {
      beforeSend: function() {
        return appChannel.trigger("sync:start", this);
      },
      complete: function() {
        return appChannel.trigger("sync:stop", this);
      }
    };
    return appChannel.on("when:fetched", function(entities, callback) {
      var xhrs;
      xhrs = _.chain([entities]).flatten().pluck("_fetch").value();
      return $.when.apply($, xhrs).done(function() {
        return callback();
      });
    });
  });

}).call(this);
