// Generated by CoffeeScript 1.12.2
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(["msgbus", "apps/games/list/views", "marionette", "entities/twitchtv"], function(msgBus, Views, Mn) {
    var Controller, appChannel;
    appChannel = msgBus.appChannel;
    return Controller = (function(superClass) {
      extend(Controller, superClass);

      function Controller() {
        return Controller.__super__.constructor.apply(this, arguments);
      }

      Controller.prototype.initialize = function(options) {
        var mainRegion;
        if (options == null) {
          options = {};
        }
        mainRegion = appChannel.request("default:region");
        this.entities = appChannel.request("games:top:entities");
        return appChannel.trigger("when:fetched", this.entities, (function(_this) {
          return function() {
            _this.layout = _this.getLayoutView({
              collection: _this.entities
            });
            _this.listenTo(_this.layout, "show:grid", function() {
              return _this.showGridView(_this.entities);
            });
            _this.listenTo(_this.layout, "show:bubble", function() {
              return _this.showBubbleView(_this.entities);
            });
            _this.listenTo(_this.layout, "more:games", function() {
              return appChannel.request("games:fetchmore");
            });
            _this.listenTo(_this.layout, "scroll:more", function() {
              return appChannel.request("games:fetchmore");
            });
            return mainRegion.show(_this.layout);
          };
        })(this));
      };

      Controller.prototype.showGridView = function(games) {
        var gView;
        gView = this.getGridView(games);
        return this.layout.getRegion("topGameList").show(gView);
      };

      Controller.prototype.showBubbleView = function(collection) {
        var bView;
        bView = this.getBubbleView(this.entities);
        return this.layout.getRegion("topGameList").show(bView);
      };

      Controller.prototype.getBubbleView = function(collection) {
        return new Views.GamesBubbleView({
          collection: collection
        });
      };

      Controller.prototype.getGridView = function(collection) {
        return new Views.GameGridView({
          collection: collection
        });
      };

      Controller.prototype.getLayoutView = function(options) {
        if (options == null) {
          options = {};
        }
        return new Views.Layout(options);
      };

      return Controller;

    })(Mn.Object);
  });

}).call(this);
