// Generated by CoffeeScript 1.6.3
(function() {
  define(function(require) {
    return {
      datavis: require("text!apps/db/list/templates/datavis.htm"),
      layout: require("text!apps/db/list/templates/layout.htm")
    };
  });

}).call(this);
