// Generated by CoffeeScript 1.12.1
(function() {
  define(function(require) {
    return {
      item: require("text!apps/header/list/templates/itemview.htm"),
      header: require("text!apps/header/list/templates/header.htm"),
      login: require("text!apps/header/list/templates/login.htm"),
      layout: require("text!apps/header/list/templates/layout.htm")
    };
  });

}).call(this);
