// Generated by CoffeeScript 1.6.3
(function() {
  define(function(require) {
    return {
      about: require("text!apps/oauth/show/templates/about.htm"),
      layout: require("text!apps/oauth/show/templates/layout.htm")
    };
  });

}).call(this);
