// Generated by CoffeeScript 1.12.2
(function() {
  define(["msgbus", "apps/header/list/controller"], function(msgBus, Controller) {
    var API, appChannel;
    appChannel = msgBus.appChannel;
    API = {
      list: function() {
        return new Controller;
      }
    };
    return appChannel.on("start:header:app", function() {
      return API.list();
    });
  });

}).call(this);
