// Generated by CoffeeScript 1.6.3
(function() {
  define(function(require) {
    return {
      about: require("text!apps/about/show/templates/about.htm"),
      layout: require("text!apps/about/show/templates/layout.htm"),
      alert: require("text!apps/about/show/templates/alert.htm")
    };
  });

}).call(this);
