// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['apps/about/show/templates', 'views/_base', 'd3'], function(Templates, AppView) {
    var Alert, DataVisLayout, _item, _ref, _ref1, _ref2;
    return {
      About: _item = (function(_super) {
        __extends(_item, _super);

        function _item() {
          _ref = _item.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        _item.prototype.template = _.template(Templates.about);

        return _item;

      })(AppView.ItemView),
      Layout: DataVisLayout = (function(_super) {
        __extends(DataVisLayout, _super);

        function DataVisLayout() {
          _ref1 = DataVisLayout.__super__.constructor.apply(this, arguments);
          return _ref1;
        }

        DataVisLayout.prototype.template = _.template(Templates.layout);

        DataVisLayout.prototype.regions = {
          aboutRegion: "#about-region",
          alertRegion: "#alert-region"
        };

        return DataVisLayout;

      })(AppView.Layout),
      Alert: Alert = (function(_super) {
        __extends(Alert, _super);

        function Alert() {
          _ref2 = Alert.__super__.constructor.apply(this, arguments);
          return _ref2;
        }

        Alert.prototype.template = _.template(Templates.alert);

        return Alert;

      })(AppView.ItemView)
    };
  });

}).call(this);
