// Generated by CoffeeScript 1.12.2
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(["marionette", "apps/about/show/templates"], function(Mn, Templates) {
    var About, AppLayout, BookRowView, BookTableBody, BookTableView, OSSTableView, OssRowView, OssTableBody;
    BookRowView = (function(superClass) {
      extend(BookRowView, superClass);

      function BookRowView() {
        return BookRowView.__super__.constructor.apply(this, arguments);
      }

      BookRowView.prototype.template = _.template(Templates.bookItem);

      BookRowView.prototype.tagName = "tr";

      return BookRowView;

    })(Mn.View);
    OssRowView = (function(superClass) {
      extend(OssRowView, superClass);

      function OssRowView() {
        return OssRowView.__super__.constructor.apply(this, arguments);
      }

      OssRowView.prototype.template = _.template(Templates.ossItem);

      OssRowView.prototype.tagName = "tr";

      return OssRowView;

    })(Mn.View);
    About = (function(superClass) {
      extend(About, superClass);

      function About() {
        return About.__super__.constructor.apply(this, arguments);
      }

      About.prototype.template = _.template(Templates.about);

      return About;

    })(Mn.View);
    BookTableBody = (function(superClass) {
      extend(BookTableBody, superClass);

      function BookTableBody() {
        return BookTableBody.__super__.constructor.apply(this, arguments);
      }

      BookTableBody.prototype.tagName = "tbody";

      BookTableBody.prototype.childView = BookRowView;

      return BookTableBody;

    })(Mn.CollectionView);
    OssTableBody = (function(superClass) {
      extend(OssTableBody, superClass);

      function OssTableBody() {
        return OssTableBody.__super__.constructor.apply(this, arguments);
      }

      OssTableBody.prototype.tagName = "tbody";

      OssTableBody.prototype.childView = OssRowView;

      return OssTableBody;

    })(Mn.CollectionView);
    BookTableView = (function(superClass) {
      extend(BookTableView, superClass);

      function BookTableView() {
        return BookTableView.__super__.constructor.apply(this, arguments);
      }

      BookTableView.prototype.template = _.template(Templates.bookTable);

      BookTableView.prototype.regions = {
        body: {
          el: 'tbody',
          replaceElement: true
        }
      };

      BookTableView.prototype.onRender = function() {
        return this.showChildView("body", new BookTableBody({
          collection: this.collection
        }));
      };

      return BookTableView;

    })(Mn.View);
    OSSTableView = (function(superClass) {
      extend(OSSTableView, superClass);

      function OSSTableView() {
        return OSSTableView.__super__.constructor.apply(this, arguments);
      }

      OSSTableView.prototype.template = _.template(Templates.ossTable);

      OSSTableView.prototype.regions = {
        body: {
          el: 'tbody',
          replaceElement: true
        }
      };

      OSSTableView.prototype.onRender = function() {
        return this.showChildView("body", new OssTableBody({
          collection: this.collection
        }));
      };

      return OSSTableView;

    })(Mn.View);
    return {
      LayoutView: AppLayout = (function(superClass) {
        extend(AppLayout, superClass);

        function AppLayout() {
          return AppLayout.__super__.constructor.apply(this, arguments);
        }

        AppLayout.prototype.template = _.template(Templates.layout);

        AppLayout.prototype.regions = {
          aboutRegion: "#about-region",
          bookRegion: "#book-region",
          ossRegion: "#oss-region"
        };

        AppLayout.prototype.onRender = function() {
          console.log('getOptions', this.getOption("bookEntities"));
          console.log('getOptions', this.getOption("ossEntities"));
          this.showChildView("aboutRegion", new About());
          this.showChildView("bookRegion", new BookTableView({
            collection: this.getOption("bookEntities")
          }));
          return this.showChildView("ossRegion", new OSSTableView({
            collection: this.getOption("ossEntities")
          }));
        };

        return AppLayout;

      })(Mn.View)
    };
  });

}).call(this);
