// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['apps/about/show/templates', 'views/_base', 'd3'], function(Templates, AppView) {
    var Book, Books, DataVisLayout, Oss, Osslist, _item, _ref, _ref1, _ref2, _ref3, _ref4, _ref5;
    Book = (function(_super) {
      __extends(Book, _super);

      function Book() {
        _ref = Book.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Book.prototype.template = _.template(Templates.bookitem);

      Book.prototype.tagName = "tr";

      return Book;

    })(AppView.ItemView);
    Oss = (function(_super) {
      __extends(Oss, _super);

      function Oss() {
        _ref1 = Oss.__super__.constructor.apply(this, arguments);
        return _ref1;
      }

      Oss.prototype.template = _.template(Templates.ossitem);

      Oss.prototype.tagName = "tr";

      return Oss;

    })(AppView.ItemView);
    return {
      Books: Books = (function(_super) {
        __extends(Books, _super);

        function Books() {
          _ref2 = Books.__super__.constructor.apply(this, arguments);
          return _ref2;
        }

        Books.prototype.template = _.template(Templates.books);

        Books.prototype.itemView = Book;

        Books.prototype.itemViewContainer = "tbody";

        return Books;

      })(AppView.CompositeView),
      Oss: Osslist = (function(_super) {
        __extends(Osslist, _super);

        function Osslist() {
          _ref3 = Osslist.__super__.constructor.apply(this, arguments);
          return _ref3;
        }

        Osslist.prototype.template = _.template(Templates.oss);

        Osslist.prototype.itemView = Oss;

        Osslist.prototype.itemViewContainer = "tbody";

        return Osslist;

      })(AppView.CompositeView),
      About: _item = (function(_super) {
        __extends(_item, _super);

        function _item() {
          _ref4 = _item.__super__.constructor.apply(this, arguments);
          return _ref4;
        }

        _item.prototype.template = _.template(Templates.about);

        return _item;

      })(AppView.ItemView),
      Layout: DataVisLayout = (function(_super) {
        __extends(DataVisLayout, _super);

        function DataVisLayout() {
          _ref5 = DataVisLayout.__super__.constructor.apply(this, arguments);
          return _ref5;
        }

        DataVisLayout.prototype.template = _.template(Templates.layout);

        DataVisLayout.prototype.regions = {
          aboutRegion: "#about-region",
          bookRegion: "#book-region",
          ossRegion: "#oss-region"
        };

        return DataVisLayout;

      })(AppView.Layout)
    };
  });

}).call(this);
