// Generated by CoffeeScript 1.9.2
(function() {
  define(["msgbus"], function(msgBus) {
    return msgBus.commands.setHandler("when:fetched", function(entities, callback) {
      var xhrs;
      xhrs = _.chain([entities]).flatten().pluck("_fetch").value();
      return $.when.apply($, xhrs).done(function() {
        return callback();
      });
    });
  });

}).call(this);
