// Generated by CoffeeScript 1.12.2
(function() {
  define(["msgbus"], function(msgBus) {
    var appChannel;
    appChannel = msgBus.appChannel;
    return appChannel.on("when:fetched", function(entities, callback) {
      var xhrs;
      xhrs = _.chain([entities]).flatten().pluck("_fetch").value();
      return $.when.apply($, xhrs).done(function() {
        return callback();
      });
    });
  });

}).call(this);
