// Generated by CoffeeScript 1.12.2
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(["backbone", "msgbus"], function(Backbone, msgBus) {
    var API, AppState, appChannel, appState;
    appChannel = msgBus.appChannel;
    AppState = (function(superClass) {
      extend(AppState, superClass);

      function AppState() {
        return AppState.__super__.constructor.apply(this, arguments);
      }

      AppState.prototype.defaults = {
        clientId: "x77jaxed6gmro98hgmv3poxrzf9dty",
        accessToken: null,
        authState: null,
        uri: "http://localhost:3000"
      };

      return AppState;

    })(Backbone.Model);
    API = {
      getAppState: function() {
        return appState;
      }
    };
    appChannel.reply("get:current:appstate", function() {
      return API.getAppState();
    });
    appChannel.reply("get:current:token", function() {
      return appState.get("accessToken");
    });
    return appState = new AppState;
  });

}).call(this);
