// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["entities/_backbone", "msgbus"], function(_Backbone, msgBus) {
    var API, AppState, appState, _ref;
    AppState = (function(_super) {
      __extends(AppState, _super);

      function AppState() {
        _ref = AppState.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      AppState.prototype.defaults = {
        clientId: "hqxyqc9bf41e6grm6txrsdcwncoxavz",
        accessToken: false,
        loginStatus: false
      };

      return AppState;

    })(_Backbone.Model);
    appState = new AppState;
    API = {
      getAppState: function() {
        return appState;
      }
    };
    msgBus.reqres.setHandler("get:current:appstate", function() {
      return API.getAppState();
    });
    return msgBus.reqres.setHandler("get:current:token", function() {
      return appState.get("accessToken");
    });
  });

}).call(this);
