// Generated by CoffeeScript 1.12.1
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(["entities/_backbone", "msgbus"], function(_Backbone, msgBus) {
    var API, Author;
    Author = (function(superClass) {
      extend(Author, superClass);

      function Author() {
        return Author.__super__.constructor.apply(this, arguments);
      }

      Author.prototype.defaults = {
        fullName: "Jack Killilea",
        twitter: "https://www.twitter.com/jack_killilea",
        github: "https://www.github.com/xjackk"
      };

      return Author;

    })(_Backbone.Model);
    API = {
      getAuthor: function() {
        return new Author;
      }
    };
    return msgBus.reqres.setHandler("get:authorModel:info", function() {
      return API.getAuthor();
    });
  });

}).call(this);
