// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["entities/_backbone", "msgbus"], function(_Backbone, msgBus) {
    var API, Author, _ref;
    Author = (function(_super) {
      __extends(Author, _super);

      function Author() {
        _ref = Author.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Author.prototype.defaults = {
        fullName: "Jack Killilea",
        twitter: "https://www.twitter.com/jack_killilea",
        github: "https://www.github.com/xjackk"
      };

      return Author;

    })(_Backbone.Model);
    API = {
      getAuthor: function() {
        return new Author;
      }
    };
    return msgBus.reqres.setHandler("get:authorModel:info", function() {
      return API.getAuthor();
    });
  });

}).call(this);
