// Generated by CoffeeScript 1.6.3
(function() {
  define(["backbone", "msgbus"], function(Backbone, msgBus) {
    var API;
    API = {
      getHeaders: function() {
        return new Backbone.Collection([
          {
            name: "d3",
            url: "#d3",
            title: "Jack's App"
          }, {
            name: "About",
            url: "#about",
            title: "About Jack's App"
          }
        ]);
      }
    };
    return msgBus.reqres.setHandler("header:entities", function() {
      return API.getHeaders();
    });
  });

}).call(this);
