// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["entities/_backbone", "msgbus"], function(_Backbone, msgBus) {
    var API, User, UsersCollection, _ref, _ref1;
    User = (function(_super) {
      __extends(User, _super);

      function User() {
        _ref = User.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      return User;

    })(_Backbone.Model);
    UsersCollection = (function(_super) {
      __extends(UsersCollection, _super);

      function UsersCollection() {
        _ref1 = UsersCollection.__super__.constructor.apply(this, arguments);
        return _ref1;
      }

      UsersCollection.prototype.model = User;

      return UsersCollection;

    })(_Backbone.Collection);
    API = {
      setCurrentUser: function(currentUser) {
        return new User(currentUser);
      }
    };
    return msgBus.reqres.setHandler("set:current:user", function(currentUser) {
      return API.setCurrentUser(currentUser);
    });
  });

}).call(this);
