// Generated by CoffeeScript 1.9.2
(function() {
  define(["jquery", "config/jquery/jquery", "config/underscore/templatesettings", "config/marionette/templatecache", "config/marionette/application", "config/backbone/sync", "entities/_fetch", "entities/twitchtv", "entities/appstate", "entities/author", "entities/reference", "entities/oss", "components/loading/controller", "bootstrap", "globalize", "text"], function() {});

}).call(this);
