// Generated by CoffeeScript 1.6.3
(function() {
  define(["config/jquery/jquery", "config/underscore/templatesettings", "config/marionette/templatecache", "config/marionette/application", "config/backbone/sync", "entities/_fetch", "entities/abstract/buttons", "entities/twitchtv", "entities/appstate", "entities/author", "entities/reference", "entities/oss", "components/form/controller", "components/loading/controller", "bootstrap", "globalize"], function() {});

}).call(this);
