// Generated by CoffeeScript 1.6.3
(function() {
  define(["config/jquery/jquery", "config/underscore/templatesettings", "config/marionette/templatecache", "config/marionette/application", "config/backbone/sync", "entities/_fetch", "entities/abstract/buttons", "entities/twitchtv", "components/form/controller", "holderjs", "bootstrap", "components/loading/controller", "entities/appstate", "entities/author"], function() {});

}).call(this);
