// Generated by CoffeeScript 1.12.2
(function() {
  define(function(require) {
    return {
      gamedetail: require("text!apps/games/detail/templates/gamedetail.htm"),
      streamitem: require("text!apps/games/detail/templates/streamitem.htm"),
      layout: require("text!apps/games/detail/templates/layout.htm")
    };
  });

}).call(this);
