// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['apps/games/detail/templates', 'views/_base', 'msgbus'], function(Templates, AppView, msgBus) {
    var GameDetail, GamesLayout, _ref, _ref1;
    return {
      Detail: GameDetail = (function(_super) {
        __extends(GameDetail, _super);

        function GameDetail() {
          _ref = GameDetail.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        GameDetail.prototype.template = _.template(Templates.gamedetail);

        GameDetail.prototype.className = "col-xs-12";

        return GameDetail;

      })(AppView.ItemView),
      Layout: GamesLayout = (function(_super) {
        __extends(GamesLayout, _super);

        function GamesLayout() {
          _ref1 = GamesLayout.__super__.constructor.apply(this, arguments);
          return _ref1;
        }

        GamesLayout.prototype.template = _.template(Templates.layout);

        GamesLayout.prototype.regions = {
          gameRegion: "#game-region",
          streamRegion: "#stream-region"
        };

        return GamesLayout;

      })(AppView.Layout)
    };
  });

}).call(this);
