// Generated by CoffeeScript 1.6.3
(function() {
  define(['underscore'], function(_) {
    return _.templateSettings = {
      evaluate: /\{\[([\s\S]+?)\]\}/g,
      interpolate: /\{\{(.+?)\}\}/g
    };
  });

}).call(this);
