// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["msgbus", "apps/top/list/views", "controller/_base"], function(msgBus, Views, AppController) {
    var Controller, _ref;
    return Controller = (function(_super) {
      __extends(Controller, _super);

      function Controller() {
        _ref = Controller.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Controller.prototype.initialize = function(options) {
        var entities,
          _this = this;
        entities = msgBus.reqres.request("games:top:entities");
        this.layout = this.getLayoutView();
        this.listenTo(this.layout, "show", function() {
          return _this.gameRegion(entities);
        });
        return this.show(this.layout, {
          loading: {
            entities: entities
          }
        });
      };

      Controller.prototype.gameRegion = function(collection) {
        var view;
        view = this.getGameView(collection);
        return this.layout.topGameRegion.show(view);
      };

      Controller.prototype.getGameView = function(collection) {
        return new Views.TopGameList({
          collection: collection
        });
      };

      Controller.prototype.getLayoutView = function() {
        return new Views.Layout;
      };

      return Controller;

    })(AppController);
  });

}).call(this);
