// Generated by CoffeeScript 1.6.3
(function() {
  define(function(require) {
    return {
      gameitem: require("text!apps/top/list/templates/gameitem.htm"),
      layout: require("text!apps/top/list/templates/layout.htm"),
      topgame: require("text!apps/top/list/templates/topgame.htm")
    };
  });

}).call(this);
