// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['apps/top/list/templates', 'views/_base', 'd3'], function(Templates, AppView) {
    var DataVisLayout, GameItem, TopGameList, _ref, _ref1, _ref2;
    GameItem = (function(_super) {
      __extends(GameItem, _super);

      function GameItem() {
        _ref = GameItem.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      GameItem.prototype.template = _.template(Templates.gameitem);

      return GameItem;

    })(AppView.ItemView);
    return {
      TopGameList: TopGameList = (function(_super) {
        __extends(TopGameList, _super);

        function TopGameList() {
          _ref1 = TopGameList.__super__.constructor.apply(this, arguments);
          return _ref1;
        }

        TopGameList.prototype.template = _.template(Templates.topgame);

        TopGameList.prototype.itemView = GameItem;

        TopGameList.prototype.itemViewContainer = "#items";

        return TopGameList;

      })(AppView.CompositeView),
      Layout: DataVisLayout = (function(_super) {
        __extends(DataVisLayout, _super);

        function DataVisLayout() {
          _ref2 = DataVisLayout.__super__.constructor.apply(this, arguments);
          return _ref2;
        }

        DataVisLayout.prototype.template = _.template(Templates.layout);

        DataVisLayout.prototype.regions = {
          topGameRegion: "#gametop-region"
        };

        return DataVisLayout;

      })(AppView.Layout)
    };
  });

}).call(this);
