// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["msgbus", "backbone", "marionette", "apps/playa/show/controller"], function(msgBus, Backbone, Marionette, Controller) {
    var API, Router, _ref;
    Router = (function(_super) {
      __extends(Router, _super);

      function Router() {
        _ref = Router.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Router.prototype.appRoutes = {
        "player": "show"
      };

      return Router;

    })(Marionette.AppRouter);
    API = {
      show: function(model) {
        return new Controller({
          model: model
        });
      }
    };
    msgBus.commands.setHandler("start:playa:app", function() {
      return new Router({
        controller: API
      });
    });
    return msgBus.events.on("app:playa:show", function(model) {
      Backbone.history.navigate("games/player/" + (model.get("game")) + "/" + (model.get("channel").display_name), {
        trigger: false
      });
      return API.show(model);
    });
  });

}).call(this);
