// Generated by CoffeeScript 1.12.2
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(["msgbus", "controller/_base", "apps/streams/list/views"], function(msgBus, AppController, Views) {
    var Controller, appChannel;
    appChannel = msgBus.appChannel;
    return Controller = (function(superClass) {
      extend(Controller, superClass);

      function Controller() {
        return Controller.__super__.constructor.apply(this, arguments);
      }

      Controller.prototype.initialize = function(options) {
        var name, streamEntities, view;
        if (options == null) {
          options = {};
        }
        name = options.name;
        console.log("streams:list:controller OPTIONS", options);
        streamEntities = appChannel.request("search:stream:entities", name);
        view = this.getLayoutView(streamEntities);
        this.listenTo(view, "childview:stream:item:clicked", function(child, args) {
          return appChannel.trigger("app:playa:show", args.model);
        });
        this.listenTo(view, "scroll:more", function() {
          return appChannel.request("streams:fetchmore");
        });
        return this.show(view, {
          loading: {
            entities: streamEntities
          }
        });
      };

      Controller.prototype.getLayoutView = function(collection) {
        return new Views.Layout({
          collection: collection
        });
      };

      return Controller;

    })(AppController);
  });

}).call(this);
