// Generated by CoffeeScript 1.12.2
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['msgbus', 'marionette', 'apps/streams/list/templates'], function(msgBus, Mn, Templates) {
    var StreamItem, StreamLayout, StreamListView, appChannel;
    appChannel = msgBus.appChannel;
    StreamItem = (function(superClass) {
      extend(StreamItem, superClass);

      function StreamItem() {
        return StreamItem.__super__.constructor.apply(this, arguments);
      }

      StreamItem.prototype.template = _.template(Templates.streamitem);

      StreamItem.prototype.tagName = "li";

      StreamItem.prototype.className = "col-md-6 col-xs-12 streamitem";

      StreamItem.prototype.triggers = {
        "click": "stream:item:clicked"
      };

      return StreamItem;

    })(Mn.View);
    StreamListView = (function(superClass) {
      extend(StreamListView, superClass);

      function StreamListView() {
        return StreamListView.__super__.constructor.apply(this, arguments);
      }

      StreamListView.prototype.childView = StreamItem;

      StreamListView.prototype.tagName = "ul";

      StreamListView.prototype.className = "list-inline";

      StreamListView.prototype.onChildviewStreamItemClicked = function(cv) {
        return appChannel.trigger("app:playa:show", cv.model);
      };

      return StreamListView;

    })(Mn.CollectionView);
    return {
      Layout: StreamLayout = (function(superClass) {
        extend(StreamLayout, superClass);

        function StreamLayout() {
          this.checkScroll = bind(this.checkScroll, this);
          return StreamLayout.__super__.constructor.apply(this, arguments);
        }

        StreamLayout.prototype.template = _.template(Templates.streams);

        StreamLayout.prototype.regions = {
          streams: {
            el: "ul",
            replaceElement: true
          }
        };

        StreamLayout.prototype.events = {
          "scroll": "checkScroll"
        };

        StreamLayout.prototype.checkScroll = function(e) {
          var margin, scrollTop, virtualHeight;
          virtualHeight = this.$("> div").height();
          scrollTop = this.$el.scrollTop() + this.$el.height();
          margin = 200;
          if ((scrollTop + margin) >= virtualHeight) {
            return this.trigger("scroll:more");
          }
        };

        StreamLayout.prototype.onRender = function() {
          return this.showChildView("streams", new StreamListView({
            collection: this.collection
          }));
        };

        return StreamLayout;

      })(Mn.View)
    };
  });

}).call(this);
