// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["entities/_backbone", "msgbus"], function(_Backbone, msgBus) {
    var API, Button, ButtonsCollection, _ref, _ref1;
    Button = (function(_super) {
      __extends(Button, _super);

      function Button() {
        _ref = Button.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Button.prototype.defaults = {
        buttonType: "button"
      };

      return Button;

    })(_Backbone.Model);
    ButtonsCollection = (function(_super) {
      __extends(ButtonsCollection, _super);

      function ButtonsCollection() {
        _ref1 = ButtonsCollection.__super__.constructor.apply(this, arguments);
        return _ref1;
      }

      ButtonsCollection.prototype.model = Button;

      return ButtonsCollection;

    })(_Backbone.Collection);
    API = {
      getFormButtons: function(buttons, model) {
        var array, buttonCollection;
        buttons = this.getDefaultButtons(buttons, model);
        array = [];
        if (buttons.cancel !== false) {
          array.push({
            type: "cancel",
            className: "btn btn-warning btn-small",
            text: buttons.cancel
          });
        }
        if (buttons.primary !== false) {
          array.push({
            type: "primary",
            className: "btn btn-success btn-small",
            text: buttons.primary,
            buttonType: "submit"
          });
        }
        if (buttons.placement === "left") {
          array.reverse();
        }
        buttonCollection = new ButtonsCollection(array);
        buttonCollection.placement = buttons.placement;
        return buttonCollection;
      },
      getDefaultButtons: function(buttons, model) {
        return _.defaults(buttons, {
          primary: model.isNew() ? "Create" : "Update",
          cancel: "Cancel",
          placement: "right"
        });
      }
    };
    return msgBus.reqres.setHandler("form:button:entities", function(buttons, model) {
      if (buttons == null) {
        buttons = {};
      }
      return API.getFormButtons(buttons, model);
    });
  });

}).call(this);
